### PR TITLE
Added method loadMessageXml() to Analyser and fixed PHPUnit tests

### PR DESCRIPTION
**Pull request by Xiro**
##### PHPUnit tests #####
I noticed the PHPUnit test  you created, but couldn't make them work without changing the structure. So I just added a phpunit.xml and a Bootstrap.php to make it work, I don't know if you actually use those test, but they will run if you simply call `phpunit` through the command prompt in the `src` directory.

Three of five tests weren't passing and I couldn't make them work either, it seems they were build on another version of the project. I just commented them out, maybe you can help me with getting them to work?

##### loadMessageXml() #####
This method will read a message XML file as they are stored in Mapping/[version]/messages and returns an array in a quite similar structure as `loadSegmentsXml`

#### loadCodesXml() ####
Will read codes xml file in a simple array. `loadCodes` is still present as it returns a result (although its pretty unstructured). I marked the old method `@deprecated`

#### loadSegmentsXml() ####
Because the methods I used in `loadMessageXml()` are working great in this method, too, I optimized it a little bit.

#### test files ####
Don't mind the amount of lines added in the last commit, these are just test files. I needed some arrays to assert them to the results of the different methods of the Analyser.

If you include one of the commits please keep in mind you need to create a tag as well for the new version. Otherwise the composer will always only check out the commits before the last tag.

### CODE REVIEW

**Comment by sabas** [comment]
For the xml loading I use a simplexml based solution with xpath in my code (which is based on the piece I released), but I never released because it's horrible :-) I look into your PR now

**Comment by sabas** [comment]
@Xiro I can't run the tests.
I tried with
```phpunit --bootstrap tests/Bootstrap.php```
In the directory

**Comment by Xiro** [comment]
The path to the bootstrap file is stored in `phpunit.xml`, so you don't need `--bootstrap` so just run:
`cd edifact`
`phpunit`

**Comment by sabas** [comment]
Different pc now, gives
```PHP Fatal error:  Class 'EDI\Analyser' not found in /home/stefano/Desktop/edifact/tests/EDITest/AnalyserTest.php on line 21
```

**Comment by Xiro** [comment]
I wonder why it worked for me, because this is clearly wrong, thanks, a little copy&paste error. How embarrassing!

**Comment by sabas** [comment]
This works for me (launches the tests included in your PR.
Could you please check if it's correct? (if it's the case do another commit :-) )
```
<?php

error_reporting(E_ALL | E_STRICT);
chdir(__DIR__);

class Bootstrap {

    public static function init()
    {
        static::initAutoloader();    
    }

    protected static function initAutoloader()
    {
        $vendorPath = static::findParentPath('vendor');
        if (file_exists($vendorPath . '/autoload.php')) {
            include $vendorPath . '/autoload.php';
        }
        spl_autoload_register(function($className) {
            $path = str_replace('\\', '/', $className);
             include_once '../src/'.$path.'.php';
        });
    }

    public static function findParentPath($path)
    {
        $dir = __DIR__;
        $previousDir = '.';
        while (!is_dir($dir . '/' . $path)) {
            $dir = dirname($dir);
            if ($previousDir === $dir) {
                return false;
            }
            $previousDir = $dir;
        }
        return $dir . '/' . $path;
    }

}

Bootstrap::init();
```

**Comment by Xiro** [comment]
Works fine and is a much cleaner solution, I pushed the commit

**Comment by sabas** [comment]
Merged, thanks! I'm checking the tests

**Comment by Xiro** [comment]
Thanks :-) Please add the tag, too

**Comment by sabas** [comment]
Done!

**Pull request merged**
