### PR TITLE
Adding UNA's reading

### PR DESCRIPTION
**Pull request by Azzurvif**
UNA's line is now read and used.
Character definition may change from one file to another.

### CODE REVIEW

**Comment by sabas** [comment]
Cool!
Question: Do you think it would be better to preg_replace only one time instead of calling the function multiple times? (Possibly it could be a performance issue on bigger files?)

**Comment by sabas** [comment]
@mtdavidson is it the same as phpcs? I never had set up these bots, would be cool to try :-)

**Comment by Azzurvif** [comment]
> Do you think it would be better to preg_replace only one time instead of calling the function multiple times?
Which function ? Which preg_replace ?

> Question 2: Is line 106 to 119 formatted correctly? (I'd like to follow psr guidelines, but I'm reading the code from the web at this time)
They aren't, I wrote them in a readable way. I can change it

**Comment by sabas** [comment]
Sorry, my head meant preg_quote, but I wrote preg_replace

**Comment by mtdavidson** [comment]
@sabas Yes its powered by PHP CS Fixer as I understand it.

**Comment by sabas** [comment]
@Azzurvif you should use spaces instead of tabs,
that section validates with phpcs (https://github.com/squizlabs/PHP_CodeSniffer) like this
```php
private function analyseUNA($line)
{
    $line = preg_replace("#^UNA#", "", $line);
    if(isset($line{0})) {
        $this->sep_comp = $line{0};
    if (isset($line{1})) {
        $this->sep_data = $line{1};
        if (isset($line{2})) {
            $this->sep_dec = $line{2};
            if (isset($line{3})) {
                $this->symb_rel = $line{3};
                if (isset($line{4})) {
                        $this->symb_rep = $line{4};
                    if (isset($line{5})) {
                            $this->symb_end = $line{5};
                    }
                }
            }
        }
    }
    }
}
```

**Comment by Azzurvif** [comment]
I updated the branch (another commit incomming because it seems a little buggy)
Concerning the preg_quote, I didn't saved the escaped char because we need it in the unwrap function. 
But indeed, I can think of a better solution

**Comment by Azzurvif** [comment]
> Then I was wondering if in this line https://github.com/sabas/edifact/blob/master/src/EDI/Parser.php#L49 we should still check for UNA segment

Same :+1: , but the error you mentionned made me think about a global solution.
I corrected the default escaping and added a boolean una_checked. I want to avoid mutiple UNA analyzes.
I also put the analyseUNA to public, and changed the acceptable parameter from "UNAXXXXXX" to "XXXXXX"). My objectif was to allow this kind of use of the Parser  :
```
$parser = new Parser();
$parser->analyseUNA("~#./!'");
// or $parser->analyseUNA("UNA/!'"); because "U" , "N" and "A" should possibly be 3 of the 6 expected characters. In a file that would mean a line like UNAUNA./'
$parser->load($myAlreadyUnwappedFileWithoutUNA)
```
Next step was to allow the use of "/" as a end line character, which is done with :
```
private static $DELIMITER = "/";
// ...
preg_quote($line{5}, self::$DELIMITER); // "/" is now included in escaped chararacters
// ...
preg_split(self::$DELIMITER.$my_text.self::$DELIMITER, $line); // $my_text contains escaped slashes
```

**Pull request merged**
