### PR TITLE
Refactor Analyser and add support for non-line-breaked files

### LINKED ISSUE #26: Analyser breaks on EDI file with no newlines
I have an EDI file without line breaks which breaks the Analyser on [line 178](https://github.com/sabas/edifact/blob/ba68f597d27c288743f8dc5e2b02b07ffd1e0910/src/EDI/Analyser.php#L178). Newlines are optional and [Wikipedia](https://en.wikipedia.org/wiki/EDIFACT#Example) even states that:

> Note: The line breaks after each segment in this example have been added for readability. There are typically no line breaks in EDI data.

This is not caught by the unit tests since `example.edi` does indeed contain line breaks.

I understand that the purpose is to show only the current segment in raw format before each explanation. Just putting line 178 inside an `if` statement would solve the problem but also remove that feature. I'm not really sure what the best course of action would be here. Perhaps making `loadEdiMessage` split on the segment separator instead of linebreaks? But that would also mean we have to actually parse parts of the message inside the Analyser.

Perhaps some refactoring is in order:

* Remove `Analyser::loadEdiMessage`
* Add functionality to read raw segment from `Parser`

This would also remove the need to load the file twice for analysis since the Parser already have it.

What do you think?

### PR DESCRIPTION
**Pull request by emilv**
Fix #26

### CODE REVIEW

**Comment by emilv** [comment]
I just realized that composer.lock maybe shouldn't be committed to a library repo. I'm so used to working on large projects (where it definitely should be included) that I committed it out of habit. Should I remove it?

**Comment by sabas** [comment]
For the composer.lock, I don't think that this package has specific version requirements, so is it really necessary?

**Comment by emilv** [comment]
It's gone!

**Comment by sabas** [comment]
LGTM
I understood what you meant!

**Comment by emilv** [comment]
:+1:

**Pull request merged**
